version: '3.9'

services:
  httpd1: # Servidor Apache 1
    container_name: httpd1
    image: httpd:latest
    working_dir: /usr/local/apache2/htdocs
    volumes:
      - /home/asir2/asir/github/sri/docker/httpd/htdocs/:/usr/local/apache2/htdocs
      - /home/asir2/asir/github/sri/docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports: 
      - '58080:80'
    expose:
      - '80'
    networks: 
      mynetwork: 
        ipv4_address: 172.28.0.80
    dns:
      - 172.28.0.53
    restart: on-failure

  httpd2: # Servidor Apache 2
    container_name: httpd2
    image: httpd:latest
    working_dir: /usr/local/apache2/htdocs 
    volumes_from:
      - httpd1
    ports: 
      - '58081:80'
    expose:
      - '80'
    networks: 
      mynetwork: 
        ipv4_address: 172.28.0.81
    dns:
      - 172.28.0.53
    restart: on-failure

  mysql: # Servidor MySQL
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - /home/asir2/asir/asir2/sri/mysql/data/:/var/lib/mysql
      - /home/asir2/asir/asir2/sri/mysql/conf/my.cnf:/etc/my.cnf
    networks:
      mynetwork:
        ipv4_address: 172.28.0.33
    ports:
      - '53306:3306'
    expose:
      - '3306'
    restart: on-failure

  postgres: # Servidor PostgreSQL
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - /home/asir2/asir/asir2/sri/postgres/data/:/var/lib/postgresql/data
      - /home/asir2/asir/asir2/sri/postgres/conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - /home/asir2/asir/asir2/sri/postgres/conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - /home/asir2/asir/asir2/sri/postgres/conf/pg_ident.conf:/var/lib/postgresql/data/pg_ident.conf
    networks:
      mynetwork:
        ipv4_address: 172.28.0.54
    ports:
      - '55432:5432'
    expose:
      - '5432'
    restart: on-failure

  dns: # Servidor DNS
    container_name: dns
    image: ubuntu/bind9:latest
    working_dir: /etc/bind
    volumes:
      - /home/asir2/asir/github/sri/docker/dns/bind/named.conf:/etc/bind/named.conf
      - /home/asir2/asir/github/sri/docker/dns/bind/named.conf.options:/etc/bind/named.conf.options
      - /home/asir2/asir/github/sri/docker/dns/bind/named.conf.local:/etc/bind/named.conf.local
      - /home/asir2/asir/github/sri/docker/dns/bind/named.conf.default-zones:/etc/bind/named.conf.default-zones
      - /home/asir2/asir/github/sri/docker/dns/lib/:/var/lib/bind/
    networks:
      mynetwork:
        ipv4_address: 172.28.0.53
    ports: 
      - '53:53/udp'
    expose:
      - '53/udp'
    restart: on-failure
  
  ubuntu: # Cliente Ubuntu
    container_name: ubuntu
    image: ubuntu:latest
    working_dir: /home
    volumes:
      - /home/asir2/asir/asir2/sri/ubuntu/home:/home
    networks:
      mynetwork:
        ipv4_address: 172.28.0.209
    stdin_open: true
    tty: true
    restart: on-failure
    dns:
      - 172.28.0.53

  firefox:
    container_name: firefox
    image: jlesage/firefox
    ports:
      - "5800:5800"
    volumes:
      - "/home/asir2/asir/asir2/sri/firefox:/config:rw"
    networks:
      mynetwork:
        ipv4_address: 172.28.0.220
    environment:
      - "TZ=Europe/Madrid"
    dns:
      - 172.28.0.53

networks: # Red Servicios
  mynetwork:
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.254

